workspace:
  base: /go
  path: src/github.com/yefengorg/nginx_rtmp

pipeline:
  unittest:
    image: library/golang:1.10
    commands:
    - go test $(go list ./... | grep -v vendor) -cover

  build:
    image: library/golang:1.10-alpine
    environment:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
    commands:
    - go build -a -tags netgo -ldflags '-w' -o ./bin/uploader github.com/yefengorg/nginx_rtmp
    when:
      branch:
      - master

  publish:
    image: plugins/docker
    repo: yefengorg/nginx_rtmp
    secrets: [ docker_username, docker_password ]
    tag: latest